# Site settings
title: Ali Sufyan
email: hello@alisufyan.net
url: https://alisufyan.net/
description: "Construction Planner"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: alisufyan.net
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/_AliSufyan
  - title: linkedin
    url: https://www.linkedin.com/in/alisufyan/

# Build settings
markdown: kramdown
permalink: pretty
